New properties for tuning blueprint deployment
apache/aries pull request #91
Opened 2018-11-09 15:49 UTC by philippberger

VM property "org.apache.aries.blueprint.default.timeout" can be used to
define the default time out. The default value is changed from 5min to
15min.

VM property "org.apache.aries.blueprint.extender.threads" can be used to
define the count of threads used for deployment. The default value is
changed from 3 to 10 threads.

2019-02-01 14:40 UTC, cschneider requested changes
I am in favour of this change. I noted some small improvements below.

2019-02-01 14:40 UTC, cschneider commented on blueprint/blueprint-core/src/main/java/org/apache/aries/blueprint/container/BlueprintContainerImpl.java
> +            timeout = Long.getLong(DEFAULT_TIMEOUT_PROPERTY, timeout);
I propose to log the actual timeout used if it differs from the default.

2019-02-01 14:40 UTC, cschneider commented on blueprint/blueprint-core/src/main/java/org/apache/aries/blueprint/container/BlueprintExtender.java
> +                int extenderThreads = 10;
We should keep the default of 3. So people who do not change it do not see a different behaviour.

2019-02-01 14:40 UTC, cschneider commented on blueprint/blueprint-core/src/main/java/org/apache/aries/blueprint/container/BlueprintExtender.java
> +                    extenderThreads = Integer.getInteger(EXTENDER_THREADS_PROPERTY, extenderThreads);
Like for the timeout the number of threads should be logged if it was changed by the user.

2019-02-04 13:39 UTC, cschneider approved these changes
Looks good now.
We are currently moving this repo to git. If it is ok I will wait a few days for the migration to succeed.
On git the merge will be simpler and retain your authorship.

2019-02-04 13:55 UTC, philippberger commented
> Looks good now.
> We are currently moving this repo to git. If it is ok I will wait a few days for the migration to succeed.
> On git the merge will be simpler and retain your authorship.

Sure, that's okay.
Thank you!

2019-02-24 11:12 UTC, cschneider commented
I just applied the PR to trunk. Can you check and close this PR if it is fine now?

2019-02-25 07:11 UTC, philippberger commented
Looks good, thanks.

2019-11-18 08:16 UTC, closed without merging